export { default as Hero } from "./Hero";
export { default as About } from "./About";
export { default as Vision } from "./Vision";
export { default as Projects } from "./Projects";
export { default as Marquee } from "./Marquee";
export { default as Services } from "./Services";
export { default as Testimonials } from "./Testimonials";
export { default as FAQ } from "./FAQ";
export { default as Contact } from "./Contact";
